using Amazon.CDK;
using Amazon.CDK.AWS.S3;
using Amazon.CDK.AWS.CloudFront;
using Amazon.CDK.AWS.CloudFront.Origins;
using Amazon.CDK.AWS.S3.Deployment;
using Constructs;

namespace ContosoUniversityCdk.Constructs
{
    public class FrontendConstruct : Construct
    {
        public IBucket WebsiteBucket { get; }
        public IDistribution CloudFrontDistribution { get; }

        public FrontendConstruct(Construct scope, string id) : base(scope, id)
        {
            // Create S3 bucket for static website hosting
            // The bucket will store the built React application assets
            WebsiteBucket = new Bucket(this, "WebsiteBucket", new BucketProps
            {
                // Bucket name will be auto-generated by CloudFormation
                // Public access is blocked by default - CloudFront will access via OAI
                BlockPublicAccess = BlockPublicAccess.BLOCK_ALL,
                
                // Enable versioning for better asset management
                Versioned = false,
                
                // Automatically delete objects when the stack is destroyed (for dev/test)
                // In production, consider using RETAIN
                RemovalPolicy = RemovalPolicy.DESTROY,
                AutoDeleteObjects = true,
                
                // Enable encryption at rest
                Encryption = BucketEncryption.S3_MANAGED
            });

            // Create Origin Access Identity for CloudFront to access S3
            // This allows CloudFront to access the private S3 bucket
            var originAccessIdentity = new OriginAccessIdentity(this, "OAI", new OriginAccessIdentityProps
            {
                Comment = "OAI for Contoso University website"
            });

            // Grant CloudFront OAI read access to the S3 bucket
            WebsiteBucket.GrantRead(originAccessIdentity);

            // Create CloudFront distribution with S3 origin
            CloudFrontDistribution = new Distribution(this, "WebsiteDistribution", new DistributionProps
            {
                // Configure S3 origin with Origin Access Identity
                DefaultBehavior = new BehaviorOptions
                {
                    Origin = new S3Origin(WebsiteBucket, new S3OriginProps
                    {
                        OriginAccessIdentity = originAccessIdentity
                    }),
                    // Allow GET and HEAD methods for static content
                    AllowedMethods = AllowedMethods.ALLOW_GET_HEAD,
                    // Cache policy optimized for static content
                    CachePolicy = CachePolicy.CACHING_OPTIMIZED,
                    // Compress content automatically
                    Compress = true,
                    // Viewer protocol policy - redirect HTTP to HTTPS
                    ViewerProtocolPolicy = ViewerProtocolPolicy.REDIRECT_TO_HTTPS
                },
                
                // Set default root object to index.html
                DefaultRootObject = "index.html",
                
                // Configure error responses for SPA routing
                // When a 404 or 403 occurs (e.g., /students route), serve index.html
                // This allows React Router to handle the routing client-side
                ErrorResponses = new[]
                {
                    new ErrorResponse
                    {
                        HttpStatus = 404,
                        ResponseHttpStatus = 200,
                        ResponsePagePath = "/index.html",
                        Ttl = Duration.Minutes(5)
                    },
                    new ErrorResponse
                    {
                        HttpStatus = 403,
                        ResponseHttpStatus = 200,
                        ResponsePagePath = "/index.html",
                        Ttl = Duration.Minutes(5)
                    }
                },
                
                // Price class - use North America and Europe for cost optimization
                PriceClass = PriceClass.PRICE_CLASS_100,
                
                // Enable HTTPS with default CloudFront certificate
                // For custom domain, would need to provide certificate ARN
                MinimumProtocolVersion = SecurityPolicyProtocol.TLS_V1_2_2021,
                
                // Enable IPv6
                EnableIpv6 = true,
                
                // Comment for identification
                Comment = "Contoso University React UI Distribution"
            });

            // Output the bucket name for reference
            new CfnOutput(this, "WebsiteBucketName", new CfnOutputProps
            {
                Value = WebsiteBucket.BucketName,
                Description = "S3 bucket name for website hosting"
            });

            // Output the CloudFront distribution URL
            new CfnOutput(this, "CloudFrontUrl", new CfnOutputProps
            {
                Value = $"https://{CloudFrontDistribution.DistributionDomainName}",
                Description = "CloudFront distribution URL for the React UI"
            });

            // Output the CloudFront distribution ID for cache invalidation
            new CfnOutput(this, "CloudFrontDistributionId", new CfnOutputProps
            {
                Value = CloudFrontDistribution.DistributionId,
                Description = "CloudFront distribution ID"
            });

            // Deploy React build artifacts to S3 and invalidate CloudFront cache
            // This will upload the contents of the dist folder to S3
            // and automatically invalidate the CloudFront cache
            new BucketDeployment(this, "DeployWebsite", new BucketDeploymentProps
            {
                // Source: built React application from the dist folder
                // The React app should be built before running cdk deploy
                Sources = new[] { Source.Asset("../contoso-university-ui/dist") },
                
                // Destination: S3 bucket
                DestinationBucket = WebsiteBucket,
                
                // CloudFront distribution to invalidate
                Distribution = CloudFrontDistribution,
                
                // Invalidate all paths in CloudFront cache on deployment
                // This ensures users get the latest version immediately
                DistributionPaths = new[] { "/*" },
                
                // Prune old files - remove files from S3 that are not in the source
                Prune = true,
                
                // Set cache control headers for optimal caching
                CacheControl = new[]
                {
                    CacheControl.FromString("max-age=31536000,public,immutable")
                },
                
                // Memory allocated to the Lambda function that performs the deployment
                MemoryLimit = 512
            });
        }
    }
}
