<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>ContosoUniversity</AssemblyName>
    <OutputType>Exe</OutputType>
    <RootNamespace>ContosoUniversity</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Web.Infrastructure">
      <HintPath>packages\Microsoft.Web.Infrastructure.2.0.1\lib\net40\Microsoft.Web.Infrastructure.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Helpers">
      <HintPath>packages\Microsoft.AspNet.WebPages.3.2.9\lib\net45\System.Web.Helpers.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Mvc">
      <HintPath>packages\Microsoft.AspNet.Mvc.5.2.9\lib\net45\System.Web.Mvc.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Optimization">
      <HintPath>packages\Microsoft.AspNet.Web.Optimization.1.1.3\lib\net40\System.Web.Optimization.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Razor">
      <HintPath>packages\Microsoft.AspNet.Razor.3.2.9\lib\net45\System.Web.Razor.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.WebPages">
      <HintPath>packages\Microsoft.AspNet.WebPages.3.2.9\lib\net45\System.Web.WebPages.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.WebPages.Deployment">
      <HintPath>packages\Microsoft.AspNet.WebPages.3.2.9\lib\net45\System.Web.WebPages.Deployment.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.WebPages.Razor">
      <HintPath>packages\Microsoft.AspNet.WebPages.3.2.9\lib\net45\System.Web.WebPages.Razor.dll</HintPath>
    </Reference>
    <Reference Include="WebGrease">
      <HintPath>packages\WebGrease.1.5.2\lib\WebGrease.dll</HintPath>
    </Reference>
    <Reference Include="Antlr3.Runtime">
      <HintPath>packages\Antlr.3.4.1.9004\lib\Antlr3.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CodeDom.Providers.DotNetCompilerPlatform">
      <HintPath>packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.1\lib\net45\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Services/LoggingService.cs"></Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="Scripts\jquery-3.4.1.intellisense.js"></None>
    <None Include="Scripts\jquery.validate-vsdoc.js"></None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="App_Data\"></Folder>
  </ItemGroup>
  <ItemGroup>
    <None Include="Project_Readme.txt"></None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0"></PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.12"></PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.8"></PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.13"></PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8"></PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7"></PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8"></PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.2"></PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.9"></PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0"></PackageReference>
    <PackageReference Include="EntityFramework" Version="6.5.1"></PackageReference>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="[7.0.0, )"></PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.0.0"></PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3"></PackageReference>
    <PackageReference Include="bootstrap" Version="5.3.3"></PackageReference>
    <PackageReference Include="jQuery.Validation" Version="1.21.0"></PackageReference>
    <PackageReference Include="jQuery" Version="3.7.1"></PackageReference>
    <PackageReference Include="NETStandard.Library" Version="2.0.3"></PackageReference>
    <PackageReference Include="Microsoft.jQuery.Unobtrusive.Validation" Version="4.0.0"></PackageReference>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.2"></PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0"></PackageReference>
    <PackageReference Include="System.Collections.Immutable" Version="8.0.0"></PackageReference>
    <PackageReference Include="Microsoft.Identity.Client" Version="4.58.1"></PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.2"></PackageReference>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0"></PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.2"></PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="8.0.8"></PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.8"></PackageReference>
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0"></PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8"></PackageReference>
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.0"></PackageReference>
    <PackageReference Include="Microsoft.Data.SqlClient.SNI.runtime" Version="5.1.0"></PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1"></PackageReference>
    <PackageReference Include="Modernizr" Version="2.8.3"></PackageReference>
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="9.0.1"></PackageReference>
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0"></PackageReference>
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="8.0.0"></PackageReference>
    <PackageReference Include="System.Memory" Version="4.5.5"></PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="9.0.2"></PackageReference>
    <PackageReference Include="System.Buffers" Version="4.6.0"></PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2"></PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2"></PackageReference>
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0"></PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.0"></PackageReference>
    <PackageReference Include="System.Numerics.Vectors" Version="4.6.0"></PackageReference>
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.2"></PackageReference>
  </ItemGroup>
  <Target AfterTargets="AfterBuild" Name="CopySQLClientNativeBinaries">
    <Copy DestinationFiles="$(OutputPath)Microsoft.Data.SqlClient.SNI.x64.dll" SkipUnchangedFiles="true" SourceFiles="$(MSBuildProjectDirectory)\packages\Microsoft.Data.SqlClient.SNI.runtime.2.1.1\runtimes\win-x64\native\Microsoft.Data.SqlClient.SNI.dll"></Copy>
    <Copy DestinationFiles="$(OutputPath)Microsoft.Data.SqlClient.SNI.x86.dll" SkipUnchangedFiles="true" SourceFiles="$(MSBuildProjectDirectory)\packages\Microsoft.Data.SqlClient.SNI.runtime.2.1.1\runtimes\win-x86\native\Microsoft.Data.SqlClient.SNI.dll"></Copy>
    <Copy DestinationFolder="$(OutputPath)x64\" SkipUnchangedFiles="true" SourceFiles="$(MSBuildProjectDirectory)\packages\Microsoft.Data.SqlClient.SNI.runtime.2.1.1\runtimes\win-x64\native\Microsoft.Data.SqlClient.SNI.dll"></Copy>
    <Copy DestinationFolder="$(OutputPath)x86\" SkipUnchangedFiles="true" SourceFiles="$(MSBuildProjectDirectory)\packages\Microsoft.Data.SqlClient.SNI.runtime.2.1.1\runtimes\win-x86\native\Microsoft.Data.SqlClient.SNI.dll"></Copy>
  </Target>
  <ProjectExtensions>
    <VisualStudio>
      <FlavorProperties GUID="{349c5851-65df-11da-9384-00065b846f21}"></FlavorProperties>
    </VisualStudio>
  </ProjectExtensions>
</Project>