#!/bin/bash

# Note: This script explains why Docker is required for CDK deployment

set -e

echo "=========================================="
echo "CDK Deployment Requirement"
echo "=========================================="
echo ""
echo "⚠️  Docker Desktop is required to deploy this CDK stack."
echo ""
echo "Why?"
echo "-----"
echo "The CDK stack uses ContainerImage.FromAsset() which builds"
echo "Docker images locally during CDK synthesis. This is a core"
echo "requirement of how CDK handles container assets."
echo ""
echo "=========================================="
echo "Install Docker Desktop"
echo "=========================================="
echo ""
echo "Download and install Docker Desktop for your platform:"
echo ""
echo "  macOS:   https://docs.docker.com/desktop/install/mac-install/"
echo "  Windows: https://docs.docker.com/desktop/install/windows-install/"
echo "  Linux:   https://docs.docker.com/desktop/install/linux-install/"
echo ""
echo "Docker Desktop is free for:"
echo "  • Personal use"
echo "  • Small businesses (< 250 employees AND < \$10M revenue)"
echo "  • Education and open source projects"
echo ""
echo "=========================================="
echo "After Installing Docker"
echo "=========================================="
echo ""
echo "Run these commands to deploy:"
echo ""
echo "  cd ContosoUniversityCdk"
echo "  cdk bootstrap  # First time only"
echo "  cdk deploy"
echo ""
echo "Or use the automated script:"
echo ""
echo "  ./scripts/deploy.sh"
echo ""
echo "=========================================="
echo "Alternatives (If You Cannot Install Docker)"
echo "=========================================="
echo ""
echo "1. Deploy from CI/CD"
echo "   Use GitHub Actions, GitLab CI, or AWS CodePipeline"
echo ""
echo "2. Deploy from another machine"
echo "   Use a machine where Docker is already installed"
echo ""
echo "3. Modify the CDK stack (Advanced)"
echo "   Rewrite to use pre-built ECR images"
echo "   See DOCKER_REQUIREMENT.md for details"
echo ""
echo "For more information, see:"
echo "  • DOCKER_REQUIREMENT.md"
echo "  • DEPLOYMENT_OPTIONS.md"
echo ""

echo ""
echo "=========================================="
echo "✅ Deployment Complete!"
echo "=========================================="
echo ""

# Save outputs to file
echo "Saving stack outputs..."
cdk deploy --outputs-file outputs.json --require-approval never 2>/dev/null || true

if [ -f outputs.json ]; then
    echo ""
    echo "Stack Outputs:"
    echo "=============="
    cat outputs.json | jq '.' 2>/dev/null || cat outputs.json
    echo ""
fi

echo "Next Steps:"
echo "1. Access your application at the CloudFront URL shown above"
echo "2. Check CloudWatch logs if you encounter any issues"
echo "3. Run './scripts/deploy-ui.sh' to update the frontend"
echo ""
echo "For troubleshooting, see: NO_DOCKER_DEPLOYMENT.md"
